version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: lms-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/sql/init_lms_db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - lms-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}
    depends_on:
      - mysql
    ports:
      - "${HOST_PORT}:${SERVER_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: docker

      # === DATABASE ===
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_TIMEZONE: ${DB_TIMEZONE}
      DB_CREATE_IF_NOT_EXIST: ${DB_CREATE_IF_NOT_EXIST}
      DB_USE_SSL: ${DB_USE_SSL}
      DB_ALLOW_PUBLIC_KEY_RETRIEVAL: ${DB_ALLOW_PUBLIC_KEY_RETRIEVAL}
      DB_POOL_SIZE: ${DB_POOL_SIZE}
      DB_POOL_MIN_IDLE: ${DB_POOL_MIN_IDLE}
      DB_CONNECTION_TIMEOUT: ${DB_CONNECTION_TIMEOUT}
      DB_IDLE_TIMEOUT: ${DB_IDLE_TIMEOUT}
      DB_MAX_LIFETIME: ${DB_MAX_LIFETIME}
      DB_TEST_QUERY: ${DB_TEST_QUERY}

      # === APP / SERVER ===
      APP_NAME: ${APP_NAME}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_CONTEXT_PATH: ${SERVER_CONTEXT_PATH}
      SERVER_MAX_THREADS: ${SERVER_MAX_THREADS}
      SERVER_MIN_THREADS: ${SERVER_MIN_THREADS}
      SERVER_CONNECTION_TIMEOUT: ${SERVER_CONNECTION_TIMEOUT}
      SERVER_ACCEPT_COUNT: ${SERVER_ACCEPT_COUNT}

      # === JPA / HIBERNATE ===
      JPA_DDL_AUTO: ${JPA_DDL_AUTO}
      JPA_SHOW_SQL: ${JPA_SHOW_SQL}
      HIBERNATE_DIALECT: ${HIBERNATE_DIALECT}
      HIBERNATE_FORMAT_SQL: ${HIBERNATE_FORMAT_SQL}
      HIBERNATE_SQL_COMMENTS: ${HIBERNATE_SQL_COMMENTS}
      HIBERNATE_BATCH_SIZE: ${HIBERNATE_BATCH_SIZE}
      HIBERNATE_ORDER_INSERTS: ${HIBERNATE_ORDER_INSERTS}
      HIBERNATE_ORDER_UPDATES: ${HIBERNATE_ORDER_UPDATES}

      # === JWT ===
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
      JWT_RESET_PASSWORD_EXPIRATION: ${JWT_RESET_PASSWORD_EXPIRATION}
      JWT_ISSUER: ${JWT_ISSUER}

      # === CORS & FRONTEND ===
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS}
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS}
      CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS}
      CORS_MAX_AGE: ${CORS_MAX_AGE}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      FRONTEND_LOGIN_URL: ${FRONTEND_LOGIN_URL}

      # === MAIL ===
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH}
      MAIL_STARTTLS_ENABLE: ${MAIL_STARTTLS_ENABLE}
      MAIL_CONNECTION_TIMEOUT: ${MAIL_CONNECTION_TIMEOUT}
      MAIL_TIMEOUT: ${MAIL_TIMEOUT}
      MAIL_WRITE_TIMEOUT: ${MAIL_WRITE_TIMEOUT}

      # === FILE UPLOAD ===
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
      MAX_REQUEST_SIZE: ${MAX_REQUEST_SIZE}
      FILE_SIZE_THRESHOLD: ${FILE_SIZE_THRESHOLD}
      UPLOAD_TEMP_DIR: ${UPLOAD_TEMP_DIR}

      # === JSON ===
      JACKSON_TIMEZONE: ${JACKSON_TIMEZONE}
      JACKSON_DATE_FORMAT: ${JACKSON_DATE_FORMAT}
      JACKSON_INCLUSION: ${JACKSON_INCLUSION}

      # === OTP CACHE ===
      OTP_MAXIMUM_SIZE: ${OTP_MAXIMUM_SIZE}
      OTP_EXPIRE_AFTER: ${OTP_EXPIRE_AFTER}
      OTP_MAX_ATTEMPTS: ${OTP_MAX_ATTEMPTS}
      OTP_INITIAL_CAPACITY: ${OTP_INITIAL_CAPACITY}
      OTP_MAX_RESEND: ${OTP_MAX_RESEND}
      OTP_RESEND_COOLDOWN: ${OTP_RESEND_COOLDOWN}

      # === SWAGGER ===
      SWAGGER_API_DOCS_PATH: ${SWAGGER_API_DOCS_PATH}
      SWAGGER_UI_PATH: ${SWAGGER_UI_PATH}
      SWAGGER_ENABLED: ${SWAGGER_ENABLED}
      SWAGGER_UI_ENABLED: ${SWAGGER_UI_ENABLED}
      SWAGGER_OPERATIONS_SORTER: ${SWAGGER_OPERATIONS_SORTER}
      SWAGGER_TAGS_SORTER: ${SWAGGER_TAGS_SORTER}
      SWAGGER_DISPLAY_REQUEST_DURATION: ${SWAGGER_DISPLAY_REQUEST_DURATION}
      SWAGGER_SHOW_ACTUATOR: ${SWAGGER_SHOW_ACTUATOR}

      # === ACTUATOR ===
      ACTUATOR_EXPOSED_ENDPOINTS: ${ACTUATOR_EXPOSED_ENDPOINTS}
      ACTUATOR_BASE_PATH: ${ACTUATOR_BASE_PATH}
      ACTUATOR_HEALTH_SHOW_DETAILS: ${ACTUATOR_HEALTH_SHOW_DETAILS}
      ACTUATOR_HEALTH_SHOW_COMPONENTS: ${ACTUATOR_HEALTH_SHOW_COMPONENTS}
      ACTUATOR_HEALTH_DB: ${ACTUATOR_HEALTH_DB}
      ACTUATOR_HEALTH_MAIL: ${ACTUATOR_HEALTH_MAIL}

      # === ERROR HANDLING ===
      ERROR_INCLUDE_MESSAGE: ${ERROR_INCLUDE_MESSAGE}
      ERROR_INCLUDE_BINDING: ${ERROR_INCLUDE_BINDING}
      ERROR_INCLUDE_STACKTRACE: ${ERROR_INCLUDE_STACKTRACE}

      # === LOGGING ===
      LOG_LEVEL_ROOT: ${LOG_LEVEL_ROOT}
      LOG_LEVEL_APP: ${LOG_LEVEL_APP}
      LOG_LEVEL_SPRING_WEB: ${LOG_LEVEL_SPRING_WEB}
      LOG_LEVEL_SPRING_SECURITY: ${LOG_LEVEL_SPRING_SECURITY}
      LOG_LEVEL_HIBERNATE_SQL: ${LOG_LEVEL_HIBERNATE_SQL}
      LOG_LEVEL_HIBERNATE_PARAMS: ${LOG_LEVEL_HIBERNATE_PARAMS}

    networks:
      - lms-net

volumes:
  mysql_data:

networks:
  lms-net: