# application-docker.template.yaml

# === Profile Activation ===
spring:
  config:
    activate:
      on-profile: docker

  # === Application Metadata ===
  application:
    name: ${APP_NAME:your-application-name}

  # === Database Configuration ===
  datasource:
    # URL to your MySQL database inside Docker network
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:your_database_name}?serverTimezone=${DATABASE_TIMEZONE:Asia/Ho_Chi_Minh}&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:your_db_username}
    password: ${DB_PASSWORD:your_db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # === JPA & Hibernate ===
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: ${HIBERNATE_FORMAT_SQL:true}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # === File Upload Configuration ===
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:15MB}

# === Server Configuration ===
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/your-project-name}

# === App Configuration ===
application:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:15m}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:7d}
      reset-password-expiration: ${JWT_RESET_PASSWORD_EXPIRATION:15m}
      issuer: ${JWT_ISSUER:LMS}

  frontend:
    login-url: ${FRONTEND_LOGIN_URL}

  cache:
    otp:
      maximumSize: ${OTP_MAXIMUM_SIZE:10000}
      expireAfterWrite: ${OTP_EXPIRE_AFTER:5m}
      maxAttempts: ${OTP_MAX_ATTEMPTS:5}
      initialCapacity: ${OTP_INITIAL_CAPACITY:100}
      max-resend: ${OTP_MAX_RESEND:3}
      resend-cooldown: ${OTP_RESEND_COOLDOWN:60s}

# === Swagger/OpenAPI Configuration ===
springdoc:
  api-docs:
    path: ${SWAGGER_API_DOCS_PATH:/v3/api-docs}
  swagger-ui:
    path: ${SWAGGER_UI_PATH:/swagger-docs}
    operations-sorter: ${SWAGGER_OPERATIONS_SORTER:method}
    tags-sorter: ${SWAGGER_TAGS_SORTER:alpha}
    display-request-duration: ${SWAGGER_DISPLAY_REQUEST_DURATION:true}
  show-actuator: ${SWAGGER_SHOW_ACTUATOR:true}

# === Actuator Configuration ===
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_EXPOSED_ENDPOINTS:health,info,env,metrics,beans}
  endpoint:
    health:
      show-details: ${ACTUATOR_HEALTH_SHOW_DETAILS:always}

# === Logging Configuration ===
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:DEBUG}
    com.yourcompany.yourproject: ${LOG_LEVEL_APP:DEBUG}
