# === Profile Activation ===
# This file is loaded when the 'local' profile is active
spring:
  config:
    activate:
      on-profile: profile-name # Recommended profile name for local development

  # === Application Metadata ===
  application:
    name: your-application-name

  # === Database Configuration ===
  datasource:
    # URL to your MySQL database. Add flags for timezone and auto-create database (for dev).
    url: jdbc:mysql://localhost:3306/your_database_name?serverTimezone=${database.timezone:Asia/Ho_Chi_Minh}&createDatabaseIfNotExist=true
    username: your_db_username # <-- Replace with your DB username
    password: your_db_password # <-- Replace with your DB password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # === JPA & Hibernate ===
  jpa:
    hibernate:
      # Use 'update' for dev convenience, or 'none' if using Flyway.
      # For production, it must be 'none'.
      ddl-auto: update
    # Show SQL queries in the console (recommended for dev, disable for prod).
    show-sql: true
    properties:
      hibernate:
        # Use the correct dialect for MySQL 8.
        dialect: org.hibernate.dialect.MySQL8Dialect
        # Format the SQL output for better readability (recommended for dev, disable for prod).
        format_sql: true

  # === File Upload Configuration ===
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

# === Server Configuration ===
server:
  # The application port. Use a placeholder with a default value.
  port: ${server.port:8080}
  servlet:
    context-path: /api/your-project-name

# === Swagger/OpenAPI Configuration (for dev/docs) ===
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-docs
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  show-actuator: true

# === Actuator Configuration ===
# Endpoints for monitoring and health checks (adjust for dev vs. prod).
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,beans
  endpoint:
    health:
      show-details: always

# === Logging Configuration ===
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.yourcompany.yourproject: DEBUG